apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-image
          image: us.gcr.io/iron-entropy-285002/frontend:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
            name: frontend
          env:
            - name: CI
              value: 'true'
            - name: REACT_ENV
              value: 'prod'
            - name: REACT_APP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: fb_api_key
            - name: REACT_APP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: fb_project_id
            - name: REACT_APP_MESSAGING_SENDER_ID
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: fb_sender_id
            - name: REACT_APP_APP_ID
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: fb_app_id
            - name: REACT_APP_MEASUREMENT_ID
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: fb_measurement_id
      imagePullSecrets:
        - name: us-gcr-io
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
    name: frontend-port
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: frontend-service
          servicePort: 3000