apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-image
          image: us.gcr.io/iron-entropy-285002/frontend:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
            name: frontend
          env:
            - name: CI 
              value: 'true'
      imagePullSecrets:
        - name: us-gcr-io
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
    name: frontend-port
---
  apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    name: frontend-ingress
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
  spec:
    rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: frontend-service
            servicePort: 3000